version: '2.1'
services:
  zk1:
    image: zookeeper 
    hostname: zk1
    ports:
    - 2181:2181
    volumes:
    - /opt/elk/data/elk/zookeeperdata:/opt/product/data/elk/zookeeperdata
    environment:
      ZK_ID: 1
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181

  zk2:
    image: zookeeper 
    hostname: zk2
    ports:
    - 2182:2181
    environment:
      ZK_ID: 2
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181

  zk3:
    image: zookeeper 
    hostname: zk3
    ports:
    - 2183:2181
    environment:
      ZK_ID: 3
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181

  kafka1:
    image: kafka
    hostname: kafka1
    ports:
    - 19092:9092
    volumes:
    - /opt/elk/data/elk/kafkadata:/opt/product/data/elk/kafkadata
    environment:
      KAFKA_ID: 1
      ZK_CLUSTER: zk1:2181,zk2:2181,zk3:2181

  kafka2:
    image: kafka
    hostname: kafka2
    ports:
    - 29092:9092
    environment:
      KAFKA_ID: 2
      ZK_CLUSTER: zk1:2181,zk2:2181,zk3:2181
