version: '2.1'
services:
  zk1:
    image: zookeeper 
    hostname: zk1
    ports:
    - 2181:2181
    volumes:
    - /opt/elk/data/elk/zookeeperdata:/opt/product/data/elk/zookeeperdata
    environment:
      ZK_ID: 1
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181
  zk2:
    image: zookeeper 
    hostname: zk2
    ports:
    - 2182:2181
    environment:
      ZK_ID: 2
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181
  zk3:
    image: zookeeper 
    hostname: zk3
    ports:
    - 2183:2181
    environment:
      ZK_ID: 3
      ZK_NODE_LIST: server.1=zk1:3181:4181 server.2=zk2:3181:4181 server.3=zk3:3181:4181
